name: seniorapp
description: DSC solution

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  date_format: ^1.0.6
  intl: ^0.16.0
  intent: ^1.1.0
  open_appstore: ^1.0.2
  flutter_appavailability: ^0.0.21
  shared_preferences: ^0.5.6+2
  location: ^3.0.0

  image_picker_gallery_camera: ^0.1.4
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: true
  image_path: "images/appicon.png"
flutter:
  uses-material-design: true
  fonts:
    - family: Gothic
      fonts:
      - asset: fonts/GothicA1-Regular.ttf
    - family: nixgon
      fonts:
      - asset: fonts/NIXGONFONTS M 2.0.ttf
  assets:
    - images/band.png
    - images/call.png
    - images/camera.png
    - images/contact.png
    - images/cloudy.png
    - images/cloudsun.png
    - images/gallery.png
    - images/kakao.png
    - images/message.png
    - images/rain.png
    - images/rainsun.png
    - images/humidity.png
    - images/sunny.png
    - images/temperature.png
    - images/today.png
    - images/appicon.png



